### ISSUE TITLE
[Enchantement/Bug?] Saving each individual application settings 

### ISSUE THREAD

**Issue by ZerGo0** [catright/Wale#12]
Hey,

so I have been searching for something like this for quite a while now and I'm glad that I finally found something that fulfills my needs, so thanks fou for that. But I noticed that after you restart the application that it resets the application-specific settings which is kind of annoying because I have to set them up every time after I restart my machine.

Could you please save the application based settings as well?

Thanks

**Comment by catright** [comment]
Thank you for using Wale and a good suggestion.
I understand and absolutely agreed with your opinion.
Wale have to keep its all settings between every log-in sessions and each updates.
I've just ignored every basic functions except only an audio control due to a lack of active users.
I'll update that function very soon. But it'll not be completed in just a few couple of days.

**Comment by ZerGo0** [comment]
> Thank you for using Wale and a good suggestion.
> I understand and absolutely agreed with your opinion.
> Wale have to keep its all settings between every log-in sessions and each updates.
> I've just ignored every basic functions except only an audio control due to a lack of active users.
> I'll update that function very soon. But it'll not be completed in just a few couple of days.

Appreciated, thanks a lot.

**Comment by petKitsune** [comment]
thanks a lot.

**Comment by catright** [comment]
I'm not finished the config saving system completely. But i bring [this(v0.5.15 msi)](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.15.msi) for you.
This version of Wale saves some of the session statuses. So I reckon this version can help you.
If you still have some inconveniences, please let me know.

**Comment by ZerGo0** [comment]
> I'm not finished the config saving system completely. But i bring [this(v0.5.15 msi)](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.15.msi) for you.
> This version of Wale saves some of the session statuses. So I reckon this version can help you.
> If you still have some inconveniences, please let me know.

Thanks, this helps a lot already, just 2 things that I noticed, you should probably display the process name in brackets behind the application name to avoid stuff like this (One is the 32-bit version and the other one is the 64-bit version):
![Pre](https://i.imgur.com/d575Wkx.png)

Also seems like the "auto include" isn't enabled by default, opening a new application without being able to tab out so that you can enable it yourself will blow your ears out until you can tab out.

**Comment by catright** [comment]
1. Multiple indicators for one application

I've test with both of TeamSpeak3 x64 and x86. There is only one instance can be opened even if you run both of them. I guess that two processes are the audio sub-sessions of TeamSpeak3 instance. Wale shows every audio sessions individually, So it not a bug.
I've tried to show all sub-sessions in one indicator, but it was needed a huge change of indicator system. It might be completed in a way far future.
Or you can confirm that they are actual individual processes of TeamSpeak3 x64 and x86 by looking for them on the task manager.

Anyway I'll change tooltip message on each audio session indicator to distinguish which session is belongs to what process more easily, and also add an option to select between the normal name and process name for a name of application to show

2. Auto include

Every single audio session should be _auto included_ only except [exclude list](https://github.com/catright/Wale/wiki#exclude-the-app-from-auto-control-for-permanently). If you found the app which is not included and it's not in the exclude list, It's a bug. Please let me know the name of app and the situation.

**Comment by ZerGo0** [comment]
> 1. Multiple indicators for one application
> 
> I've test with both of TeamSpeak3 x64 and x86. There is only one instance can be opened even if you run both of them. I guess that two processes are the audio sub-sessions of TeamSpeak3 instance. Wale shows every audio sessions individually, So it not a bug.
> I've tried to show all sub-sessions in one indicator, but it was needed a huge change of indicator system. It might be completed in a way far future.
> Or you can confirm that they are actual individual processes of TeamSpeak3 x64 and x86 by looking for them on the task manager.
> 
> Anyway I'll change tooltip message on each audio session indicator to distinguish which session is belongs to what process more easily, and also add an option to select between the normal name and process name for a name of application to show
Sounds good, it's just something that I have noticed, I also noticed that when you use Firefox it will show a bunch of them which is expected, but even with the process name it would be hard to identify which one is which. I don't expect people to have audio from each process, but you might need to think of something else. I attached a screenshot to show what I mean, that's just with 1 Tab open:
![Prev](https://i.imgur.com/GR7N9fX.png)
Here is a screenshot with 5 tabs open, it gets quite ridiculous after a few more tabs:
![Prev2](https://i.imgur.com/XawxJf3.png)

> 1. Auto include
> 
> Every single audio session should be _auto included_ only except [exclude list](https://github.com/catright/Wale/wiki#exclude-the-app-from-auto-control-for-permanently). If you found the app which is not included and it's not in the exclude list, It's a bug. Please let me know the name of app and the situation.
Yea it's a bug then I guess, making a report in a bit.

**Comment by catright** [comment]
Wale controls every single audio session(wasapi) individually, that means, Wale distinguishes every audio session and show them all.
Firefox reports all of its sub processes as a audio session even if it's a background process that they are not using it as a real audio player. And also they don't report which process belongs to which tab. Firefox only reports current tab on a representative process. So I don't know which one is which. I'm sorry. I can tell only that it's intended behavior in case of firefox.
I'll change to sort sessions with it's name rather than PID to show little more organized after v0.5.17
Additionally, as I said, I've tried to show them into one indicator, but it'll take quite long time.
I'm so thank you for your impassioned assistance.

**Comment by catright** [comment]
[v0.5.17 msi](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.17.msi) is updated.

**Comment by ZerGo0** [comment]
> [v0.5.17 msi](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.17.msi) is updated.

Thank you very much 
Can you do me a favour and make the min volume level per application (0.25 currently) selectable by the user? One of my application is still way too loud even at that level, others are set to 4, but this one at 0.25 is still way too loud. Right now I have to manually set the volume for it which isn't ideal. Maybe let the user input a specific value (preferably without limits) by shift double-clicking the application name or something like that.

**Comment by ZerGo0** [comment]
> [v0.5.17 msi](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.17.msi) is updated.

Also v0.5.17 seems very unresponsive and doesn't respond sometimes unless I open Wale myself.

**Comment by ZerGo0** [comment]
@catright Any updates on this, I would try to contribute, but I can’t even build it when I git clone it.
