### ISSUE TITLE
keep files in WalePortable folder 

### ISSUE THREAD

**Issue by petKitsune** [catright/Wale#13]
nice tool, like it
but is it possible to keep the files 
%localappdata%\Wale\[folder]\[folder]\user.config
and
%appdata%\WaleAudioControl\Walelog-*.txt
in the WalePortable root folder

if not i have to make a PAF [portableapps.com] to cleanup after running
thx

**Comment by catright** [comment]
Thank you for such a good opinion.
I'm making a function to save configurations of the Wale without using windows built-in saving system that saves the file under %localappdata%.
This could be take a long time to be finished.

About %appdata%, now I'm considering to change several work directories to some other places for simplicity of file management and previlege requirement. I have to think more for now, but I definitely accommodate your suggestion on portable version.

**Comment by petKitsune** [comment]
excellent
take your time

**Comment by catright** [comment]
I'm very appreciate your patience.

**Comment by catright** [comment]
Please try [0.6.6](https://github.com/catright/Wale/blob/master/WaleSetup_0.6.6.msi)
I've changed the way to save configuration files.
