### ISSUE TITLE
[BUG] v0.1.15 Auto Include/Auto Control Enabled not working

### ISSUE THREAD

**Issue by ZerGo0** [catright/Wale#14]
There is not really much to say, it doesn't include any of the new programs that show up in Wale:
![Prev](https://i.imgur.com/zwhrAx2.gif)
My Settings:
![Prev2](https://i.imgur.com/wThNbfU.png)

My log file:
[WaleLog-20200324-092635.txt](https://github.com/catright/Wale/files/4374304/WaleLog-20200324-092635.txt)
My config:
![Prev3](https://i.imgur.com/ZbDVcC1.png)

**Comment by catright** [comment]
There was a bug when read saved session config. I fixed it and it'll be work properly after v0.5.16.

**Comment by catright** [comment]
[v0.5.17 msi](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.17.msi) is updated.
