### ISSUE TITLE
[Bug] v0.1.15 Save Button not always changing colour

### ISSUE THREAD

**Issue by ZerGo0** [catright/Wale#15]
Also noticed that since v0.1.14 the "Save" text seems to mess the button up:
![Prev](https://i.imgur.com/Vl5mFAD.gif)

The "Saved" text seems to be fine, the Reset-Button seems to be fine as well.

**Comment by catright** [comment]
I found this already. This will be fixed after v0.5.16.
Thank you for your report.

**Comment by catright** [comment]
[v0.5.17 msi](https://github.com/catright/Wale/blob/master/WaleSetup_0.5.17.msi) is updated.
