### ISSUE TITLE
Multiplier not applying without opening the panel

### ISSUE THREAD

**Issue by ZerGo0** [catright/Wale#17]
Hey,

I've noticed that when you start a new program, Wale does pick it up and controls the volume, but it doesn't apply the multiplier unless you open the panel.

I also noticed that the program-specific settings reset sometime, but I haven't found a to reproduce it.

**Comment by catright** [comment]
please try [0.6.1msi](https://github.com/catright/Wale/blob/CustomizedSettings/WaleSetup_0.6.1.msi) or [0.6.1zip](https://github.com/catright/Wale/blob/CustomizedSettings/WalePortable_0.6.1.zip).
I'm changing many thing on v0.6.x so these versions could be more unstable.

**Comment by catright** [comment]
#18 applied
[0.6.2msi](https://github.com/catright/Wale/blob/CustomizedSettings/WaleSetup_0.6.2.msi)
[0.6.2zip](https://github.com/catright/Wale/blob/CustomizedSettings/WalePortable_0.6.2.zip)

**Comment by catright** [comment]
I'm closing the issue.
If you have any further problems, feel free to re-open or create new one.
