### ISSUE TITLE
[Suggestion] Lower volume "smoothly" as well

### ISSUE THREAD

**Issue by ZerGo0** [catright/Wale#19]
Hey buddy,

what would you think about smoothly lowering the volume just like it does when it increases it? With another textbox just like the "Up-Rate" one that has a default value of like 5 or maybe 7.5 (Every user has to find their sweet spot obviously). That value controls the amount of volume down so the clipping isn't there anymore in really loud situations and so on.

I will most likely take a look at it myself, but I'm not sure if I will be able to find it and figure it out myself.

**Comment by catright** [comment]
I've seperated target and limit -clipping- levels. So now you have some headroom for clipping and it'll smooth the volume changes. Wale still tries to make output level to target, but now it only cuts the volume when the output is exceed the limit level. Wale will never exceed the limit level even if you set it to lower than a target.
Please use limit level carefully. If you set 'limit' too high than 'target', you'll get big explosion of noise.
