### ISSUE TITLE
Question : If it safe to use with CSGO? Can it trigger a VAC ban?

### ISSUE THREAD

**Issue by killazZooM** [catright/Wale#20]
I love the software but was wondering if it is safe to use in CSGO. Can it trigger a VAC ban? 

Thanks for your job and sorry for asking here.

**Comment by mikeloeven** [comment]
i dont see how it is adjusting the window's volume sliders on the system side It doesn't inject or modify any running game code

**Comment by catright** [comment]
I didn't experienced such thing when I play various games. And also I didn't get any report about it. So it might be ok. BUT I'm sorry. I CAN'T GUARANTEE ANYTHING.
If anyone played CS:GO, please report it for him.

**Comment by mikeloeven** [comment]
Can you clarify how WALE adjusts the volume? As long as WALE is not hooking the game executable or injecting code it will not be flagged by anti cheat. these only look for programs that are manipulating the game files or memory locations.

**Comment by catright** [comment]
Wale adjusts windows volume mixer using WASAPI and only get process name and icon from each process to distinguish and display what it is.
