### ISSUE TITLE
Exempted applications volume sliders set to 0 when WALE Initially launched

### ISSUE THREAD

**Issue by mikeloeven** [catright/Wale#21]
If you have a program that needs  to be exempt from WALE for example VOIP or other communication software WALE seems to initially set all volume sliders to 0 when the programis first launched. This includes software that has auto Include disabled. This has been causing some issues with Discord and Guilded Please add code to make sure that when the program launches it will not set volume sliders for exempted applications to 0

**Comment by catright** [comment]
I'm sorry for your inconvenience.
I'll fix it as fast as i can.

**Comment by catright** [comment]
Please try 0.6.13 [msi](https://github.com/catright/Wale/blob/master/WaleSetup_0.6.13.msi) or [zip](https://github.com/catright/Wale/blob/master/WalePortable_0.6.13.zip)
