### ISSUE TITLE
Wale 0.7.1 or later does not recognize more than 6 processes.

### ISSUE THREAD

**Issue by mutaguchi** [catright/Wale#29]
Since Wale 0.7.1, the volume control works correctly if up to six processes are outputting audio, but the seventh and later processes do not appear in the window and the volume control does not work for those that do not appear.

Versions below Wale 0.7.0 do not have this problem.

**Comment by catright** [comment]
Thank you for your feedback. I'll take a look soon.

**Comment by RoboJin** [comment]
Any update on this issue or this project has being abandon? :( This is a good software thou but stuck at using 0.7 version for now

**Comment by catright** [comment]
I'm sorry for late but I'm having some hard time for my real life now. so it might take little more time I guess. I really appreciate your patient and loving the WALE.

**Comment by RoboJin** [comment]
Don't be sorry, Take your time and take care. At least i know this project are not being abandon <3

**Comment by catright** [comment]
This might fixed on [0.7.5](https://github.com/catright/Wale/blob/master/WaleSetup_0.7.5.msi)
Please take a look!

**Comment by RoboJin** [comment]
Welcome back, I can confirm it's fixed

**Comment by catright** [comment]
good to hear that
